- name: configure {{ component}} server
  hosts: "{{ component}}"
  become: yes
  roles: 
  - "{{ component}}"

# Run the cmd with the required argument
# cmd: ansible-playbook main.yaml -e component=db