- name: install nginx
  dnf:
    name: nginx
    state: installed #latest or installed both are same

# - name: start & enable nginx
#   service:
#     name: nginx
#     state: started
#     enabled: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: Unsipping a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

#if there is change in config, system restart is required

- name: Copy a expenxe.conf file on the remote machine
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx 


- name: Restart nginx 
  service:
    name: nginx
    state: restarted
    enabled: true

    
